Mimir/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

from base import views


urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^auth/", include('django.contrib.auth.urls')),

    re_path(r"^$", views.home, name="home"),

    # Applications
    re_path(r"^base/", include('base.urls')),
    re_path(r"^movies/", include('movies.urls')),
    re_path(r"^books/", include('books.urls')),
    re_path(r"^games/", include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/urls.py
from django.urls import re_path

from . import views
from movies import views as views_movies

urlpatterns = [
    re_path(r"^$", views.index, name="base_home"),

    re_path(r"^tags$", views.tagsList, name="tags_list"),
    re_path(r"^tags/api/search$", views.tagsAPISearch, name="tags_api_search"),
    re_path(r"^tags/(?P<id>[0-9]+)$", views.tagInfo, name="tag_info"),
    re_path(r"^tags/(?P<id>[0-9]+)/edit$", views.tagEdit, name="tag_edit"),
    re_path(r"^tags/(?P<id>[0-9]+)/delete$", views.tagDelete, name="tag_delete"),
    re_path(r"^tags/(?P<tag_id>[0-9]+)/export_movies$", views_movies.export_tag_movies, name="tag_export_movies"),

    re_path(r"^persons$", views.personsList, name="persons_list"),
    re_path(r"^persons/create$", views.personCreate, name="person_create"),
    re_path(r"^persons/search$", views.personsSearch, name="persons_search"),
    re_path(r"^persons/api/list$", views.personsAPIList, name="persons_api_list"),
    re_path(r"^persons/api/search$", views.personsAPISearch, name="persons_api_search"),
    re_path(r"^persons/(?P<id>[0-9]+)$", views.personInfo, name="person_info"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit$", views.personEdit, name="person_edit"),
    re_path(r"^persons/(?P<id1>[0-9]+)/merge/(?P<id2>[0-9]+)$", views.personMerge, name="person_merge"),
    re_path(r"^persons/(?P<id>[0-9]+)/delete$", views.personDelete, name="person_delete"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_event$", views.personAddEvent, name="person_add_event"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_relation$", views.personAddRelation, name="person_add_relation"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_tag$", views.personAddTag, name="person_add_tag"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_attribute$", views.personAddAttribute, name="person_add_attribute"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_link$", views.personAddLink, name="person_add_link"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_events$", views.personEditEvents, name="person_edit_events"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_relations$", views.personEditRelations, name="person_edit_relations"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_tags$", views.personEditTags, name="person_edit_tags"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_attributes$", views.personEditAttributes, name="person_edit_attributes"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_links$", views.personEditLinks, name="person_edit_links"),

    re_path(r"^groups$", views.groupsList, name="groups_list"),
    re_path(r"^groups/create$", views.groupCreate, name="group_create"),
    re_path(r"^groups/api/search$", views.groupsAPISearch, name="groups_api_search"),
    re_path(r"^groups/(?P<id>[0-9]+)$", views.groupInfo, name="group_info"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit$", views.groupEdit, name="group_edit"),
    re_path(r"^groups/(?P<id>[0-9]+)/delete$", views.groupDelete, name="group_delete"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_member$", views.groupAddMember, name="group_add_member"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_attribute$", views.groupAddAttribute, name="group_add_attribute"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_link$", views.groupAddLink, name="group_add_link"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_members$", views.groupEditMembers, name="group_edit_members"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_attributes$", views.groupEditAttributes, name="group_edit_attributes"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_links$", views.groupEditLinks, name="group_edit_links"),

    re_path(r"^countries$", views.countriesList, name="countries_list"),
    re_path(r"^countries/create$", views.countryCreate, name="country_create"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})$", views.countryInfo, name="country_info"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})/edit$", views.countryEdit, name="country_edit"),

    re_path(r"^languages$", views.languagesList, name="languages_list"),
    re_path(r"^languages/create$", views.languageCreate, name="language_create"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})$", views.languageInfo, name="language_info"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})/edit$", views.languageEdit, name="language_edit"),

    #re_path(r"^events$", views.eventsList, name="events_list"),
]

games/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^$", views.index, name="games_home"),

    re_path(r"^games$", views.gamesList, name="games_list"),
    re_path(r"^games/create$", views.gameCreate, name="game_create"),
    re_path(r"^games/api/list$", views.gamesAPIList, name="games_api_list"),
    re_path(r"^games/api/search$", views.gamesAPISearch, name="games_api_search"),
    re_path(r"^games/(?P<id>[0-9]+)$", views.gameInfo, name="game_info"),
    re_path(r"^games/(?P<id>[0-9]+)/edit$", views.gameEdit, name="game_edit"),
    re_path(r"^games/(?P<id>[0-9]+)/delete$", views.gameDelete, name="game_delete"),
    re_path(r"^games/(?P<id>[0-9]+)/add_attribute$", views.gameAddAttribute, name="game_add_attribute"),
    re_path(r"^games/(?P<id>[0-9]+)/add_tag$", views.gameAddTag, name="game_add_tag"),
    re_path(r"^games/(?P<id>[0-9]+)/add_link$", views.gameAddLink, name="game_add_link"),
    re_path(r"^games/(?P<id>[0-9]+)/edit_attributes$", views.gameEditAttributes, name="game_edit_attributes"),
    re_path(r"^games/(?P<id>[0-9]+)/edit_tags$", views.gameEditTags, name="game_edit_tags"),
    re_path(r"^games/(?P<id>[0-9]+)/edit_links$", views.gameEditLinks, name="game_edit_links"),
    re_path(r"^games/(?P<id>[0-9]+)/edit_user$", views.gameEditUserInfo, name="game_edit_user"),

    re_path(r"^sagas$", views.sagasList, name="games_sagas_list"),
    re_path(r"^sagas/create$", views.sagaCreate, name="games_saga_create"),
    re_path(r"^sagas/(?P<id>[0-9]+)$", views.sagaInfo, name="games_saga_info"),
    re_path(r"^sagas/(?P<id>[0-9]+)/edit$", views.sagaEdit, name="games_saga_edit"),
    re_path(r"^sagas/(?P<id>[0-9]+)/delete$", views.sagaDelete, name="games_saga_delete"),
    re_path(r"^sagas/(?P<id>[0-9]+)/add_game$", views.sagaAddGame, name="games_saga_add_game"),
    re_path(r"^sagas/(?P<id>[0-9]+)/edit_games$", views.sagaEditGames, name="games_saga_edit_games"),

    re_path(r"^search$", views.gamesSearch, name="games_search"),

    re_path(r"^library$", views.gamesLibrary, name="games_library"),
]

games/models.py
import os
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _, pgettext

from base.models import Attribute, Link, Tag


def random_filename(instance, filename):
    ext = os.path.splitext(filename)[1].lower()
    if ext == ".jpeg":
        ext = ".jpg"
    filename = "%s%s" % (uuid.uuid4(), ext)
    return os.path.join("games", filename)


class Game(models.Model):
    title = models.CharField(verbose_name=_("Title"), max_length=150, blank=False)
    title_vo = models.CharField(verbose_name=_("Original title"), max_length=150, blank=True)
    year = models.IntegerField(verbose_name=_("Year"), blank=True, null=True)
    editor = models.CharField(verbose_name=_("Editor"), max_length=150, blank=True)
    developper = models.CharField(verbose_name=_("Developper"), max_length=150, blank=True)
    platform = models.CharField(verbose_name=_("Platform"), max_length=150, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    image = models.ImageField(verbose_name=_("Image"), upload_to=random_filename, null=True, blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Game")
        verbose_name_plural = _("Games")
        ordering = ["title"]


class GameAttribute(Attribute):
    game = models.ForeignKey(Game, related_name="attributes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Game") + " - " + _("Attribute")
        verbose_name_plural = _("Games") + " - " + _("Attributes")
        #ordering = ["name"]
        db_table = "games_" + "game_attributes"


class GameLink(Link):
    game = models.ForeignKey(Game, related_name="links", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Game") + " - " + _("Link")
        verbose_name_plural = _("Games") + " - " + _("Links")
        #ordering = ["name"]
        db_table = "games_" + "game_links"


class GameTag(models.Model):
    game = models.ForeignKey(Game, related_name="tags", on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, verbose_name=_("Tag"), related_name="games", on_delete=models.CASCADE)
    info = models.CharField(verbose_name=_("Information"), max_length=100, blank=True)

    class Meta:
        verbose_name = _("Game") + " - " + _("Tag")
        verbose_name_plural = _("Games") + " - " + _("Tags")
        ordering = ["tag__name"]
        db_table = "games_" + "game_tags"


class Saga(models.Model):
    title = models.CharField(verbose_name=_("Title"), max_length=100, blank=False)
    title_vo = models.CharField(verbose_name=_("Original title"), max_length=100, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = pgettext("The saga", "Saga")
        verbose_name_plural = _("Sagas")
        ordering = ["title"]


class SagaGame(models.Model):
    saga = models.ForeignKey(Saga, related_name="games", on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name=_("Game"), related_name="sagas", on_delete=models.CASCADE)

    class Meta:
        verbose_name = pgettext("The saga", "Saga") + " - " + _("Game")
        verbose_name_plural = _("Sagas") + " - " + _("Games")
        order_with_respect_to = "saga"
        unique_together = ("saga", "game")
        db_table = "games_" + "saga_games"


class GameUser(models.Model):
    game = models.ForeignKey(Game, verbose_name=_("Game"), related_name="users", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=_("User"), related_name="games", on_delete=models.CASCADE)
    bought = models.BooleanField(verbose_name=_("Bought"), default=False)
    location = models.CharField(verbose_name=_("Location"), max_length=100, blank=True)
    played = models.BooleanField(verbose_name=_("Played"), default=False)
    finished = models.BooleanField(verbose_name=_("Finished"), default=False)
    notes = models.TextField(verbose_name=_("Notes"), blank=True)

    class Meta:
        verbose_name = _("Game") + " - " + _("User")
        verbose_name_plural = _("Games") + " - " + _("Users")
        unique_together = ("game", "user")
        db_table = "games_" + "game_users"

games/forms.py

from django.forms import ModelForm, Textarea, HiddenInput, IntegerField, CharField, Select, FileInput
from django.utils.translation import gettext as _

from base.models import Tag
from .models import Game, Saga, SagaGame, GameAttribute, GameLink, GameTag, GameUser


class GameForm(ModelForm):
    image_clear = CharField(widget=HiddenInput(), max_length=1, required=False, initial="0")

    def save(self, commit=True):
        image_clear_value = self.cleaned_data.get("image_clear")
        if image_clear_value == "1":
            self.instance.image = None

        return super(ModelForm, self).save(commit=commit)

    class Meta:
        model = Game
        fields = ["title", "title_vo", "year", "editor", "developper", "platform", "info", "image", "image_clear"]
        widgets = {
            "info": Textarea(attrs={"rows": 4}),
            "image": FileInput(),
        }


class GameAttributeForm(ModelForm):

    class Meta:
        model = GameAttribute
        fields = ["name", "value"]


class GameLinkForm(ModelForm):

    class Meta:
        model = GameLink
        fields = ["name", "uri", "lang"]


# TODO: make a generic class
class GameTagForm(ModelForm):
    tag_id = IntegerField(widget=HiddenInput(), required=False)
    tag_select = IntegerField(label=_("Tag"), widget=Select(attrs={"class": "select_tag"}), required=False)
    tag_name = CharField(widget=HiddenInput(), max_length=100, required=False)

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        if hasattr(self.instance, "tag") and self.instance.tag:
            self.initial["tag_id"] = self.instance.tag.id
            self.initial["tag_name"] = self.instance.tag.name
        else:
            self.initial["tag_id"] = None
            self.initial["tag_name"] = ""

    def _clean_fields(self, *args, **kwargs):
        tagId = int(self.data.get(self.add_prefix("tag_select")))

        if tagId < 0:
            tag = Tag.objects.create(name=self.data.get(self.add_prefix("tag_name")))
        else:
            tag = Tag.objects.get(id=tagId)

        self.instance.tag = tag
        self.data = self.data.copy()
        self.data[self.add_prefix("tag")] = self.instance.tag.id

        super(ModelForm, self)._clean_fields(*args, **kwargs)

    class Meta:
        model = GameTag
        fields = ["tag_select", "tag_name", "tag", "info"]
        widgets = {
            "tag": HiddenInput(),
        }


class GameTagFormClassic(ModelForm):
    tag_name = CharField(label=_("Tag name"), max_length=100)

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields["tag"].required = False
        if hasattr(self.instance, "tag"):
            self.initial["tag_name"] = self.instance.tag.name
        else:
            self.initial["tag_name"] = ""

    def save(self, commit=True):
        name = self.cleaned_data.get("tag_name").strip()
        if self.initial["tag_name"] != name:
            tag = Tag.objects.get_or_create(name=name)[0]
            self.instance.tag = tag
        return super(ModelForm, self).save(commit=commit)

    class Meta:
        model = GameTag
        fields = ["tag", "tag_name", "info"]
        widgets = {
            "tag": HiddenInput(),
        }


class SagaForm(ModelForm):

    class Meta:
        model = Saga
        fields = ["title", "title_vo", "info"]
        widgets = {
            "info": Textarea(attrs={"rows": 4}),
        }


class SagaGameForm(ModelForm):
    game_id = IntegerField(label=_("Title"), widget=Select(attrs={"class": "select_game"}), required=False)
    game_title = CharField(widget=HiddenInput(), max_length=150, required=False)

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        if hasattr(self.instance, "game"):
            self.initial["game_id"] = self.instance.game.id
            self.initial["game_title"] = self.instance.game.title
            if self.instance.game.year:
                self.initial["game_title"] += " (%s)" % self.instance.game.year
        else:
            self.initial["game_id"] = None
            self.initial["game_title"] = ""

    def save(self, commit=True):
        if self.instance.game is None and self.cleaned_data.get("game_id"):
            self.instance.game = Game.objects.get(id=int(self.cleaned_data.get("game_id")))

        return super(ModelForm, self).save(commit=commit)

    class Meta:
        model = SagaGame
        fields = ["game_id", "game_title", "game"]
        widgets = {
            "game": HiddenInput(),
        }


class GameUserForm(ModelForm):

    class Meta:
        model = GameUser
        fields = ["bought", "location", "played", "finished", "notes"]
        widgets = {
            "notes": Textarea(attrs={"rows": 4}),
        }

games/templates/games/base.html
{% extends 'base_sidebar.html' %}

{% load i18n %}

{% block title %}
{% translate 'Games' %} - Mimir
{% endblock %}

{% block nav_sidebar %}
{% include 'games/sidebar.html' %}
{% endblock nav_sidebar %}

games/templates/games/saga_add_game.html
{% extends 'games/base.html' %}

{% load static %}
{% load i18n %}
{% load mimir %}

{% block content_title %}
<a href="{% url 'games_saga_info' saga.id|stringformat:'06d' %}">{% translate 'Saga' context 'The saga' %} <q><i>{{ saga.title }}</i></q></a> - {% translate 'Add game' %}
{% endblock %}

{% block title %}
{{ saga.title }} - {% translate 'Games' %} - Mimir
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}" media="all" />
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/select2/select2.min.js' %}"></script>
<script src="{% static 'js/select2/i18n/fr.js' %}"></script>

<script>
$(function() {
    function formatGame(game) {
        var markup = '<strong>' + game.title + '</strong>';
        if (game.year) {
            markup += ' <span class="small">(' + game.year + ')</span>';
        }
        return markup;
    }

    function formatGameSelection(game) {
        var value = game.title;
        if (game.year) {
            value += ' (' + game.year + ')';
        }
        return value;
    }

    $("select.select_game").select2({
        ajax: {
            url: "{% url 'games_api_search' %}{% if saga.games.count > 0 %}?exclude={% for game in saga.games.all %}{% if not forloop.first %},{% endif %}{{ game.game.id }}{% endfor %}{% endif %}",
            dataType: 'json',
            delay: 250,
            data: function(params) {
                return {
                    q: params.term,
                    page: params.page
                };
            },
            processResults: function(data, params) {
                params.page = params.page || 1;

                for (var i = 0; i < data.items.length; ++i) {
                    data.items[i]['text'] = data.items[i]['title'];
                }

                return {
                    results: data.items,
                    pagination: {
                        more: data.incomplete_results
                    }
                };
            },
            cache: true
        },
        escapeMarkup: function(markup) { return markup; },
        minimumInputLength: 1,
        templateResult: formatGame,
        templateSelection: formatGameSelection,
    }).on("change", function(e) {
        $('#id_game_title').val($('#id_game_id option:selected').text());
        $('#id_game').val($('#id_game_id').val());
    });

    $(document).on('select2:open', function(e) {
        document.querySelector(`[aria-controls="select2-${e.target.id}-results"]`).focus();
    });

    $('#id_game_id').val({value: $('#id_game').val(), text: $('#id_game_title').val()});
});
</script>
{% endblock %}

{% block content %}

  {{ form.non_field_errors }}

  {% if form.subject.errors %}
  <ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
  </ol>
  {% endif %}

  <div class="box box-primary">
    <form action="{% url 'games_saga_add_game' saga.id|stringformat:'06d' %}" method="post" class="form">
      {% csrf_token %}

      <div class="box-body">
        {% for field in form.hidden_fields %}
          {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group row{% if field.errors %} has-error{% endif %}">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
          <div class="col-sm-10">{{ field|field_add_class:'form-control input-sm' }}</div>
          {% if field.help_text %}
            <p class="form-text text-muted">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="box-footer">
        <input type="submit" class="btn btn-primary center-block" value="{% translate 'Submit' %}" />
      </div>
    </form>
  </div>

{% endblock %}

games/templates/games/saga_info.html
{% extends 'games/base.html' %}

{% load static %}
{% load i18n %}
{% load mimir %}

{% block footer_right %}
{% if saga.creation %}{% translate 'Creation:' %} {{ saga.creation }}.{% endif %}
{% if saga.modification %}{% translate 'Last modification:' %} {{ saga.modification }}.{% endif %}
{% endblock %}

{% block title %}
{{ saga.title }} - {% translate 'Games' %} - Mimir
{% endblock %}

{% block content_header %}
<section class="content-header">
  <h1>{% translate 'Saga' context 'The saga' %} <q><i>{{ saga.title }}</i></q>
    {% if user.is_authenticated %}
    <div class="pull-right">
      <a href="{% url 'games_saga_edit' saga.id|stringformat:'06d' %}" class="btn btn-sm btn-warning">{% translate 'Edit' %}</a>
      <a href="{% url 'games_saga_delete' saga.id|stringformat:'06d' %}" class="btn btn-sm btn-danger">{% translate 'Delete' %}</a>
    </div>
    {% endif %}
  </h1>
</section>
{% endblock content_header %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/datatables/dataTables.min.css' %}">
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/datatables/datatables.min.js' %}"></script>

<script>
$(function() {
    $("#games_list").DataTable({
        "paging"      : false,
        "lengthChange": false,
        "searching"   : false,
        "ordering"    : true,
        "info"        : false,
        "autoWidth"   : true,
        "language": {
            "processing":     "Traitement en cours...",
            "search":         "Rechercher&nbsp;:",
            "lengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
            "info":           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
            "infoEmpty":      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
            "infoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
            "infoPostFix":    "",
            "loadingRecords": "Chargement en cours...",
            "zeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
            "emptyTable":     "Aucune donnée disponible dans le tableau.",
            "paginate": {
                "first":      "{% translate 'First' %}",
                "previous":   "{% translate 'Previous' %}",
                "next":       "{% translate 'Next' %}",
                "last":       "{% translate 'Last' %}"
            },
            "aria": {
                "sortAscending":  ": activer pour trier la colonne par ordre croissant",
                "sortDescending": ": activer pour trier la colonne par ordre décroissant"
            }
        },
    });
});
</script>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-md-4">
      <div class="box box-solid box-info">
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>{% translate 'Title' %}</dt><dd><i>{{ saga.title }}</i></dd>
            {% if saga.title_vo %}<dt>{% translate 'Original title' %}</dt><dd><i>{{ saga.title_vo }}</i></dd>{% endif %}
          </dl>
        </div>
      </div>
    </div>
  </div>

  {% if saga.info %}
  <div class="box box-solid box-info">
    <div class="box-header with-border">
      <h3 class="box-title">{% translate 'Information' %}</h3>
    </div>
    <div class="box-body">{{ saga.info|linebreaks }}</div>
  </div>
  {% endif %}

  <div class="box box-solid box-info">
    <div class="box-header with-border">
      <h3 class="box-title">{% translate 'Games' %}</h3>
      <div class="box-tools pull-right">
        {% if perms.games.change_sagagame %}
        <a href="{% url 'games_saga_edit_games' saga.id|stringformat:'06d' %}" class="btn btn-box-tool" title="{% translate 'Edit games' %}">
          <i class="fa fa-edit"></i>
        </a>
        {% endif %}
        {% if perms.games.add_sagagame %}
        <a href="{% url 'games_saga_add_game' saga.id|stringformat:'06d' %}" class="btn btn-box-tool" title="{% translate 'Add game' %}">
          <i class="fa fa-plus-square"></i>
        </a>
        {% endif %}
        <button type="button" class="btn btn-box-tool" data-widget="collapse">
          <i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body">
      {% if games|length > 0 %}
      <table class="table table-bordered table-stripped table-hover" id="games_list">
        <thead>
          <tr>
            <th>{% translate 'Order' %}</th>
            <th>{% translate 'Title' %}</th>
            <th>{% translate 'Year' %}</th>
            <th>{% translate 'Editor' %}</th>
            <th>{% translate 'Platform' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for sagaGame in games %}
          <tr>
            <td>{{ sagaGame|get_order }}</td>
            <td><a href="{% url 'game_info' sagaGame.game.id|stringformat:'06d' %}" class="{% if sagaGame.finished %}game_finished{% elif sagaGame.played %}game_played{% else %}game_not_played{% endif %}"><i>{{ sagaGame.game.title }}</i></a></td>
            <td>{% if sagaGame.game.year %}{{ sagaGame.game.year }}{% endif %}</td>
            <td>{{ sagaGame.game.editor }}</td>
            <td>{{ sagaGame.game.platform }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>{% translate 'No games.' %}</p>
      {% endif %}
    </div>
  </div>

{% endblock %}