Mimir/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

from base import views


urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^auth/", include('django.contrib.auth.urls')),

    re_path(r"^$", views.home, name="home"),

    # Applications
    re_path(r"^base/", include('base.urls')),
    re_path(r"^movies/", include('movies.urls')),
    re_path(r"^books/", include('books.urls')),
    re_path(r"^games/", include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/urls.py
from django.urls import re_path

from . import views
from movies import views as views_movies

urlpatterns = [
    re_path(r"^$", views.index, name="base_home"),

    re_path(r"^tags$", views.tagsList, name="tags_list"),
    re_path(r"^tags/api/search$", views.tagsAPISearch, name="tags_api_search"),
    re_path(r"^tags/(?P<id>[0-9]+)$", views.tagInfo, name="tag_info"),
    re_path(r"^tags/(?P<id>[0-9]+)/edit$", views.tagEdit, name="tag_edit"),
    re_path(r"^tags/(?P<id>[0-9]+)/delete$", views.tagDelete, name="tag_delete"),
    re_path(r"^tags/(?P<tag_id>[0-9]+)/export_movies$", views_movies.export_tag_movies, name="tag_export_movies"),

    re_path(r"^persons$", views.personsList, name="persons_list"),
    re_path(r"^persons/create$", views.personCreate, name="person_create"),
    re_path(r"^persons/search$", views.personsSearch, name="persons_search"),
    re_path(r"^persons/api/list$", views.personsAPIList, name="persons_api_list"),
    re_path(r"^persons/api/search$", views.personsAPISearch, name="persons_api_search"),
    re_path(r"^persons/(?P<id>[0-9]+)$", views.personInfo, name="person_info"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit$", views.personEdit, name="person_edit"),
    re_path(r"^persons/(?P<id1>[0-9]+)/merge/(?P<id2>[0-9]+)$", views.personMerge, name="person_merge"),
    re_path(r"^persons/(?P<id>[0-9]+)/delete$", views.personDelete, name="person_delete"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_event$", views.personAddEvent, name="person_add_event"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_relation$", views.personAddRelation, name="person_add_relation"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_tag$", views.personAddTag, name="person_add_tag"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_attribute$", views.personAddAttribute, name="person_add_attribute"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_link$", views.personAddLink, name="person_add_link"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_events$", views.personEditEvents, name="person_edit_events"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_relations$", views.personEditRelations, name="person_edit_relations"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_tags$", views.personEditTags, name="person_edit_tags"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_attributes$", views.personEditAttributes, name="person_edit_attributes"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_links$", views.personEditLinks, name="person_edit_links"),

    re_path(r"^groups$", views.groupsList, name="groups_list"),
    re_path(r"^groups/create$", views.groupCreate, name="group_create"),
    re_path(r"^groups/api/search$", views.groupsAPISearch, name="groups_api_search"),
    re_path(r"^groups/(?P<id>[0-9]+)$", views.groupInfo, name="group_info"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit$", views.groupEdit, name="group_edit"),
    re_path(r"^groups/(?P<id>[0-9]+)/delete$", views.groupDelete, name="group_delete"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_member$", views.groupAddMember, name="group_add_member"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_attribute$", views.groupAddAttribute, name="group_add_attribute"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_link$", views.groupAddLink, name="group_add_link"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_members$", views.groupEditMembers, name="group_edit_members"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_attributes$", views.groupEditAttributes, name="group_edit_attributes"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_links$", views.groupEditLinks, name="group_edit_links"),

    re_path(r"^countries$", views.countriesList, name="countries_list"),
    re_path(r"^countries/create$", views.countryCreate, name="country_create"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})$", views.countryInfo, name="country_info"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})/edit$", views.countryEdit, name="country_edit"),

    re_path(r"^languages$", views.languagesList, name="languages_list"),
    re_path(r"^languages/create$", views.languageCreate, name="language_create"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})$", views.languageInfo, name="language_info"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})/edit$", views.languageEdit, name="language_edit"),

    #re_path(r"^events$", views.eventsList, name="events_list"),
]

books/urls.py
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^$", views.index, name="books_home"),

    re_path(r"^works$", views.worksList, name="works_list"),
    re_path(r"^works/create$", views.workCreate, name="work_create"),
    re_path(r"^works/api/list$", views.worksAPIList, name="works_api_list"),
    re_path(r"^works/api/search$", views.worksAPISearch, name="works_api_search"),
    re_path(r"^works/(?P<id>[0-9]+)$", views.workInfo, name="work_info"),
    re_path(r"^works/(?P<id>[0-9]+)/edit$", views.workEdit, name="work_edit"),
    re_path(r"^works/(?P<id>[0-9]+)/delete$", views.workDelete, name="work_delete"),
    re_path(r"^works/(?P<id>[0-9]+)/add_reading$", views.workAddReading, name="work_add_reading"),
    re_path(r"^works/(?P<id>[0-9]+)/add_translation$", views.workAddTranslation, name="work_add_translation"),
    re_path(r"^works/(?P<id>[0-9]+)/add_edition$", views.workAddEdition, name="work_add_edition"),
    re_path(r"^works/(?P<id>[0-9]+)/add_attribute$", views.workAddAttribute, name="work_add_attribute"),
    re_path(r"^works/(?P<id>[0-9]+)/add_ref$", views.workAddRef, name="work_add_ref"),
    re_path(r"^works/(?P<id>[0-9]+)/add_tag$", views.workAddTag, name="work_add_tag"),
    re_path(r"^works/(?P<id>[0-9]+)/add_link$", views.workAddLink, name="work_add_link"),
    re_path(r"^works/(?P<id>[0-9]+)/edit_readings$", views.workEditReadings, name="work_edit_readings"),
    re_path(r"^works/(?P<id>[0-9]+)/edit_attributes$", views.workEditAttributes, name="work_edit_attributes"),
    re_path(r"^works/(?P<id>[0-9]+)/edit_refs$", views.workEditRefs, name="work_edit_refs"),
    re_path(r"^works/(?P<id>[0-9]+)/edit_tags$", views.workEditTags, name="work_edit_tags"),
    re_path(r"^works/(?P<id>[0-9]+)/edit_links$", views.workEditLinks, name="work_edit_links"),

    re_path(r"^translations/(?P<id>[0-9]+)$", views.translationInfo, name="translation_info"),
    re_path(r"^translations/(?P<id>[0-9]+)/edit$", views.translationEdit, name="translation_edit"),
    re_path(r"^translations/(?P<id>[0-9]+)/delete$", views.translationDelete, name="translation_delete"),
    re_path(r"^translations/(?P<id>[0-9]+)/add_reading$", views.translationAddReading, name="translation_add_reading"),
    re_path(r"^translations/(?P<id>[0-9]+)/add_edition$", views.translationAddEdition, name="translation_add_edition"),
    re_path(r"^translations/(?P<id>[0-9]+)/add_attribute$", views.translationAddAttribute, name="translation_add_attribute"),
    re_path(r"^translations/(?P<id>[0-9]+)/add_tag$", views.translationAddTag, name="translation_add_tag"),
    re_path(r"^translations/(?P<id>[0-9]+)/add_link$", views.translationAddLink, name="translation_add_link"),
    re_path(r"^translations/(?P<id>[0-9]+)/edit_readings$", views.translationEditReadings, name="translation_edit_readings"),
    re_path(r"^translations/(?P<id>[0-9]+)/edit_attributes$", views.translationEditAttributes, name="translation_edit_attributes"),
    re_path(r"^translations/(?P<id>[0-9]+)/edit_tags$", views.translationEditTags, name="translation_edit_tags"),
    re_path(r"^translations/(?P<id>[0-9]+)/edit_links$", views.translationEditLinks, name="translation_edit_links"),

    re_path(r"^texts/api/search$", views.textsAPISearch, name="texts_api_search"),
    re_path(r"^texts/(?P<id>[0-9]+)$", views.textInfo, name="text_info"),

    re_path(r"^editions/create$", views.editionCreateCollection, name="edition_collection_create"),
    re_path(r"^editions/api/list$", views.editionAPIList, name="editions_api_list"),
    re_path(r"^editions/(?P<id>[0-9]+)$", views.editionInfo, name="edition_info"),
    re_path(r"^editions/(?P<id>[0-9]+)/edit$", views.editionEdit, name="edition_edit"),
    re_path(r"^editions/(?P<id>[0-9]+)/delete$", views.editionDelete, name="edition_delete"),
    re_path(r"^editions/(?P<id>[0-9]+)/duplicate$", views.editionDuplicate, name="edition_duplicate"),
    re_path(r"^editions/(?P<id>[0-9]+)/to_collection$", views.editionTransformToCollection, name="edition_to_collection"),
    re_path(r"^editions/(?P<id>[0-9]+)/to_edition$", views.editionTransformToEdition, name="edition_to_edition"),
    re_path(r"^editions/(?P<id>[0-9]+)/add_text$", views.editionAddText, name="edition_add_text"),
    re_path(r"^editions/(?P<id>[0-9]+)/add_volume$", views.editionAddVolume, name="edition_add_volume"),
    re_path(r"^editions/(?P<id>[0-9]+)/add_reading$", views.editionAddReading, name="edition_add_reading"),
    re_path(r"^editions/(?P<id>[0-9]+)/add_attribute$", views.editionAddAttribute, name="edition_add_attribute"),
    re_path(r"^editions/(?P<id>[0-9]+)/add_link$", views.editionAddLink, name="edition_add_link"),
    re_path(r"^editions/(?P<id>[0-9]+)/edit_texts$", views.editionEditTexts, name="edition_edit_texts"),
    re_path(r"^editions/(?P<id>[0-9]+)/edit_readings$", views.editionEditReadings, name="edition_edit_readings"),
    re_path(r"^editions/(?P<id>[0-9]+)/edit_attributes$", views.editionEditAttributes, name="edition_edit_attributes"),
    re_path(r"^editions/(?P<id>[0-9]+)/edit_links$", views.editionEditLinks, name="edition_edit_links"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)$", views.volumeInfo, name="volume_info"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)/edit$", views.volumeEdit, name="volume_edit"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)/delete$", views.volumeDelete, name="volume_delete"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)/add_book$", views.volumeAddBook, name="volume_add_book"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)/add_reading$", views.volumeAddReading, name="volume_add_reading"),
    re_path(r"^editions/(?P<id>[0-9]+)/(?P<vid>[0-9]+)/edit_readings$", views.volumeEditReadings, name="volume_edit_readings"),

    re_path(r"^books$", views.booksList, name="books_list"),
    re_path(r"^books/(?P<id>[0-9]+)$", views.bookInfo, name="book_info"),
    re_path(r"^books/(?P<id>[0-9]+)/edit$", views.bookEdit, name="book_edit"),
    re_path(r"^books/(?P<id>[0-9]+)/delete$", views.bookDelete, name="book_delete"),
    re_path(r"^books/(?P<id>[0-9]+)/add_reading$", views.bookAddReading, name="book_add_reading"),
    re_path(r"^books/(?P<id>[0-9]+)/edit_readings$", views.bookEditReadings, name="book_edit_readings"),

    re_path(r"^sagas$", views.sagasList, name="books_sagas_list"),
    re_path(r"^sagas/create$", views.sagaCreate, name="books_saga_create"),
    re_path(r"^sagas/(?P<id>[0-9]+)$", views.sagaInfo, name="books_saga_info"),
    re_path(r"^sagas/(?P<id>[0-9]+)/edit$", views.sagaEdit, name="books_saga_edit"),
    re_path(r"^sagas/(?P<id>[0-9]+)/delete$", views.sagaDelete, name="books_saga_delete"),
    re_path(r"^sagas/(?P<id>[0-9]+)/add_work$", views.sagaAddWork, name="books_saga_add_work"),
    re_path(r"^sagas/(?P<id>[0-9]+)/edit_works$", views.sagaEditWorks, name="books_saga_edit_works"),

    re_path(r"^lists$", views.listList, name="booklists_list"),
    re_path(r"^lists/create$", views.listCreate, name="booklist_create"),
    re_path(r"^lists/(?P<id>[0-9]+)$", views.listInfo, name="booklist_info"),
    re_path(r"^lists/(?P<id>[0-9]+)/edit$", views.listEdit, name="booklist_edit"),
    re_path(r"^lists/(?P<id>[0-9]+)/delete$", views.listDelete, name="booklist_delete"),
    re_path(r"^lists/(?P<id>[0-9]+)/add/(?P<vid>[0-9]+)$", views.listAddVolume, name="booklist_add_volume"),
    re_path(r"^lists/(?P<id>[0-9]+)/remove/(?P<vid>[0-9]+)$", views.listRemoveVolume, name="booklist_remove_volume"),

    re_path(r"^search$", views.worksSearch, name="works_search"),
    re_path(r"^readings$", views.readings, name="books_readings"),
    re_path(r"^readings/export$", views.readingsExport, name="books_readings_export"),
]

games/models.py
import os
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _, pgettext

from base.models import Attribute, Link, Tag


def random_filename(instance, filename):
    ext = os.path.splitext(filename)[1].lower()
    if ext == ".jpeg":
        ext = ".jpg"
    filename = "%s%s" % (uuid.uuid4(), ext)
    return os.path.join("games", filename)


class Game(models.Model):
    title = models.CharField(verbose_name=_("Title"), max_length=150, blank=False)
    title_vo = models.CharField(verbose_name=_("Original title"), max_length=150, blank=True)
    year = models.IntegerField(verbose_name=_("Year"), blank=True, null=True)
    editor = models.CharField(verbose_name=_("Editor"), max_length=150, blank=True)
    developper = models.CharField(verbose_name=_("Developper"), max_length=150, blank=True)
    platform = models.CharField(verbose_name=_("Platform"), max_length=150, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    image = models.ImageField(verbose_name=_("Image"), upload_to=random_filename, null=True, blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Game")
        verbose_name_plural = _("Games")
        ordering = ["title"]


class GameAttribute(Attribute):
    game = models.ForeignKey(Game, related_name="attributes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Game") + " - " + _("Attribute")
        verbose_name_plural = _("Games") + " - " + _("Attributes")
        #ordering = ["name"]
        db_table = "games_" + "game_attributes"


class GameLink(Link):
    game = models.ForeignKey(Game, related_name="links", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Game") + " - " + _("Link")
        verbose_name_plural = _("Games") + " - " + _("Links")
        #ordering = ["name"]
        db_table = "games_" + "game_links"


class GameTag(models.Model):
    game = models.ForeignKey(Game, related_name="tags", on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, verbose_name=_("Tag"), related_name="games", on_delete=models.CASCADE)
    info = models.CharField(verbose_name=_("Information"), max_length=100, blank=True)

    class Meta:
        verbose_name = _("Game") + " - " + _("Tag")
        verbose_name_plural = _("Games") + " - " + _("Tags")
        ordering = ["tag__name"]
        db_table = "games_" + "game_tags"


class Saga(models.Model):
    title = models.CharField(verbose_name=_("Title"), max_length=100, blank=False)
    title_vo = models.CharField(verbose_name=_("Original title"), max_length=100, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = pgettext("The saga", "Saga")
        verbose_name_plural = _("Sagas")
        ordering = ["title"]


class SagaGame(models.Model):
    saga = models.ForeignKey(Saga, related_name="games", on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name=_("Game"), related_name="sagas", on_delete=models.CASCADE)

    class Meta:
        verbose_name = pgettext("The saga", "Saga") + " - " + _("Game")
        verbose_name_plural = _("Sagas") + " - " + _("Games")
        order_with_respect_to = "saga"
        unique_together = ("saga", "game")
        db_table = "games_" + "saga_games"


class GameUser(models.Model):
    game = models.ForeignKey(Game, verbose_name=_("Game"), related_name="users", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=_("User"), related_name="games", on_delete=models.CASCADE)
    bought = models.BooleanField(verbose_name=_("Bought"), default=False)
    location = models.CharField(verbose_name=_("Location"), max_length=100, blank=True)
    played = models.BooleanField(verbose_name=_("Played"), default=False)
    finished = models.BooleanField(verbose_name=_("Finished"), default=False)
    notes = models.TextField(verbose_name=_("Notes"), blank=True)

    class Meta:
        verbose_name = _("Game") + " - " + _("User")
        verbose_name_plural = _("Games") + " - " + _("Users")
        unique_together = ("game", "user")
        db_table = "games_" + "game_users"

books/templates/books/book_add_reading.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'book_info' book.id|stringformat:'06d' %}"><i>{{ book.volume.title }}</i></a> ({% translate 'book' %}) - {% translate 'Add reading' %}
{% endblock %}

{% block title %}
{{ book.volume.title }} ({% translate 'book' %}) - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

books/templates/books/edition_add_attribute.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'edition_info' edition.id|stringformat:'06d' %}"><i>{{ edition.title }}</i></a> ({% translate 'edition' %}) - {% translate 'Add attribute' %}
{% endblock %}

{% block title %}
{{ edition.title }} ({% translate 'edition' %}) - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

books/templates/books/edition_add_link.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'edition_info' edition.id|stringformat:'06d' %}"><i>{{ edition.title }}</i></a> ({% translate 'edition' %}) - {% translate 'Add link' %}
{% endblock %}

{% block title %}
{{ edition.title }} ({% translate 'edition' %}) - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

books/templates/books/list_delete.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'booklist_info' list.id|stringformat:'06d' %}">{{ list.name }}</a> - {% translate 'Delete' %}
{% endblock %}

{% block title %}
{{ list.name }} - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}

  <div class="box box-primary">
    <form action="{% url 'booklist_delete' list.id|stringformat:'06d' %}" method="post" class="form">
      {% csrf_token %}
      <input type="hidden" name="delete" value="1" />

      <div class="box-body">
        <div class="alert alert-warning">
          <p>{% translate 'Are you sure you want to remove this list?' %}</p>
          <p><i class="icon fa fa-warning"></i>{% translate 'This action is irreversible.' %}</p>
        </div>
      </div>

      <div class="box-footer">
        <input type="submit" class="btn btn-danger center-block" value="{% translate 'Delete' %}" />
      </div>
    </form>
  </div>

{% endblock %}

books/templates/books/translation_add_edition.html
{% extends 'books/base.html' %}

{% load i18n %}
{% load static %}
{% load mimir %}

{% block content_title %}
<a href="{% url 'translation_info' translation.id|stringformat:'06d' %}"><i>{{ translation.original_work.title }}</i></a> ({% translate 'translation' %}) - {% translate 'Add edition' %}
{% endblock %}

{% block title %}
{{ translation.original_work.title }} ({% translate 'translation' %}) - {% translate 'Books' %} - Mimir
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}" media="all" />
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'js/fileinput/locales/fr.js' %}"></script>

<script>
$(function() {
    $('#id_image').fileinput({
        showPreview: true,
        previewFileType: 'image',
        allowedFileTypes: ['image'],
        showUpload: false,
        browseClass: 'btn btn-success',
        browseIcon: '<i class="glyphicon glyphicon-picture"></i> ',
        language: 'fr',
        maxFileCount: 1,
        autoReplace: true,
    });
});
</script>
{% endblock %}

{% block content %}

  {{ form.non_field_errors }}

  {% if form.subject.errors %}
  <ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
  </ol>
  {% endif %}

  <div class="box box-primary">
    <form action="{% url 'translation_add_edition' translation.id %}" method="post" class="form" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="box-body">
        {% for field in form.hidden_fields %}
          {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group row{% if field.errors %} has-error{% endif %}">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
          <div class="col-sm-10">{{ field|field_add_class:'form-control input-sm' }}</div>
          {% if field.help_text %}
            <p class="form-text text-muted">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="box-footer">
        <input type="submit" class="btn btn-primary center-block" value="{% translate 'Submit' %}" />
      </div>
    </form>
  </div>

{% endblock %}

books/templates/books/translation_add_reading.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'translation_info' translation.id|stringformat:'06d' %}"><i>{{ translation.original_work.title }}</i></a> ({% translate 'translation' %}) - {% translate 'Add reading' %}
{% endblock %}

{% block title %}
{{ translation.original_work.title }} ({% translate 'translation' %}) - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

books/templates/books/work_add_attribute.html
{% extends 'books/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'work_info' work.id|stringformat:'06d' %}"><i>{{ work.title }}</i></a> - {% translate 'Add attribute' %}
{% endblock %}

{% block title %}
{{ work.title }} - {% translate 'Books' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

books/templates/books/work_add_edition.html
{% extends 'books/base.html' %}

{% load i18n %}
{% load static %}
{% load mimir %}

{% block content_title %}
<a href="{% url 'work_info' work.id|stringformat:'06d' %}"><i>{{ work.title }}</i></a> - {% translate 'Add edition' %}
{% endblock %}

{% block title %}
{{ work.title }} - {% translate 'Books' %} - Mimir
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}" media="all" />
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'js/fileinput/locales/fr.js' %}"></script>

<script>
$(function() {
    $('#id_image').fileinput({
        showPreview: true,
        previewFileType: 'image',
        allowedFileTypes: ['image'],
        showUpload: false,
        browseClass: 'btn btn-success',
        browseIcon: '<i class="glyphicon glyphicon-picture"></i> ',
        language: 'fr',
        maxFileCount: 1,
        autoReplace: true,
    });
});
</script>
{% endblock %}

{% block content %}

  {{ form.non_field_errors }}

  {% if form.subject.errors %}
  <ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
  </ol>
  {% endif %}

  <div class="box box-primary">
    <form action="{% url 'work_add_edition' work.id|stringformat:'06d' %}" method="post" class="form" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="box-body">
        {% for field in form.hidden_fields %}
          {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group row{% if field.errors %} has-error{% endif %}">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
          <div class="col-sm-10">{{ field|field_add_class:'form-control input-sm' }}</div>
          {% if field.help_text %}
            <p class="form-text text-muted">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="box-footer">
        <input type="submit" class="btn btn-primary center-block" value="{% translate 'Submit' %}" />
      </div>
    </form>
  </div>

{% endblock %}