Mimir/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

from base import views


urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^auth/", include('django.contrib.auth.urls')),

    re_path(r"^$", views.home, name="home"),

    # Applications
    re_path(r"^base/", include('base.urls')),
    re_path(r"^movies/", include('movies.urls')),
    re_path(r"^books/", include('books.urls')),
    re_path(r"^games/", include('games.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/urls.py
from django.urls import re_path

from . import views
from movies import views as views_movies

urlpatterns = [
    re_path(r"^$", views.index, name="base_home"),

    re_path(r"^tags$", views.tagsList, name="tags_list"),
    re_path(r"^tags/api/search$", views.tagsAPISearch, name="tags_api_search"),
    re_path(r"^tags/(?P<id>[0-9]+)$", views.tagInfo, name="tag_info"),
    re_path(r"^tags/(?P<id>[0-9]+)/edit$", views.tagEdit, name="tag_edit"),
    re_path(r"^tags/(?P<id>[0-9]+)/delete$", views.tagDelete, name="tag_delete"),
    re_path(r"^tags/(?P<tag_id>[0-9]+)/export_movies$", views_movies.export_tag_movies, name="tag_export_movies"),

    re_path(r"^persons$", views.personsList, name="persons_list"),
    re_path(r"^persons/create$", views.personCreate, name="person_create"),
    re_path(r"^persons/search$", views.personsSearch, name="persons_search"),
    re_path(r"^persons/api/list$", views.personsAPIList, name="persons_api_list"),
    re_path(r"^persons/api/search$", views.personsAPISearch, name="persons_api_search"),
    re_path(r"^persons/(?P<id>[0-9]+)$", views.personInfo, name="person_info"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit$", views.personEdit, name="person_edit"),
    re_path(r"^persons/(?P<id1>[0-9]+)/merge/(?P<id2>[0-9]+)$", views.personMerge, name="person_merge"),
    re_path(r"^persons/(?P<id>[0-9]+)/delete$", views.personDelete, name="person_delete"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_event$", views.personAddEvent, name="person_add_event"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_relation$", views.personAddRelation, name="person_add_relation"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_tag$", views.personAddTag, name="person_add_tag"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_attribute$", views.personAddAttribute, name="person_add_attribute"),
    re_path(r"^persons/(?P<id>[0-9]+)/add_link$", views.personAddLink, name="person_add_link"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_events$", views.personEditEvents, name="person_edit_events"),
    #re_path(r"^persons/(?P<id>[0-9]+)/edit_relations$", views.personEditRelations, name="person_edit_relations"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_tags$", views.personEditTags, name="person_edit_tags"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_attributes$", views.personEditAttributes, name="person_edit_attributes"),
    re_path(r"^persons/(?P<id>[0-9]+)/edit_links$", views.personEditLinks, name="person_edit_links"),

    re_path(r"^groups$", views.groupsList, name="groups_list"),
    re_path(r"^groups/create$", views.groupCreate, name="group_create"),
    re_path(r"^groups/api/search$", views.groupsAPISearch, name="groups_api_search"),
    re_path(r"^groups/(?P<id>[0-9]+)$", views.groupInfo, name="group_info"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit$", views.groupEdit, name="group_edit"),
    re_path(r"^groups/(?P<id>[0-9]+)/delete$", views.groupDelete, name="group_delete"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_member$", views.groupAddMember, name="group_add_member"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_attribute$", views.groupAddAttribute, name="group_add_attribute"),
    re_path(r"^groups/(?P<id>[0-9]+)/add_link$", views.groupAddLink, name="group_add_link"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_members$", views.groupEditMembers, name="group_edit_members"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_attributes$", views.groupEditAttributes, name="group_edit_attributes"),
    re_path(r"^groups/(?P<id>[0-9]+)/edit_links$", views.groupEditLinks, name="group_edit_links"),

    re_path(r"^countries$", views.countriesList, name="countries_list"),
    re_path(r"^countries/create$", views.countryCreate, name="country_create"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})$", views.countryInfo, name="country_info"),
    re_path(r"^countries/(?P<code>[a-zA-Z0-9]{3})/edit$", views.countryEdit, name="country_edit"),

    re_path(r"^languages$", views.languagesList, name="languages_list"),
    re_path(r"^languages/create$", views.languageCreate, name="language_create"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})$", views.languageInfo, name="language_info"),
    re_path(r"^languages/(?P<code>[a-zA-Z0-9]{3})/edit$", views.languageEdit, name="language_edit"),

    #re_path(r"^events$", views.eventsList, name="events_list"),
]

base/models.py
from django.db import models
from django.utils.translation import gettext as _, get_language, pgettext


class Attribute(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)
    value = models.CharField(verbose_name=_("Value"), max_length=200, blank=False)

    class Meta:
        abstract = True
        ordering = ["name"]


class Language(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)
    code = models.CharField(verbose_name=_("Code"), max_length=3, primary_key=True)  # TODO: min_length=3
    iso1 = models.CharField(verbose_name=_("Code ISO 639-1"), max_length=2, blank=True, null=True)
    iso2 = models.CharField(verbose_name=_("Code ISO 639-2"), max_length=3, blank=True, null=True)
    iso3 = models.CharField(verbose_name=_("Code ISO 639-3"), max_length=3, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = pgettext("language", "Language")
        verbose_name_plural = _("Languages")
        ordering = ["name"]


class Link(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)
    uri = models.CharField(verbose_name=_("URI"), max_length=200, null=False, blank=False)
    lang = models.ForeignKey(Language, verbose_name=pgettext("language", "Language"), on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        if self.name:
            return str(self.name) + " (" + str(self.uri) + ")"
        else:
            return str(self.uri)

    class Meta:
        abstract = True
        ordering = ["name"]


class Country(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)
    code = models.CharField(verbose_name=_("Code"), max_length=3, unique=True, null=False, blank=False) # TODO: primary_key
    iso = models.CharField(verbose_name=_("Code ISO 3166-1"), max_length=3, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = pgettext("The country", "Country")
        verbose_name_plural = _("Countries")
        ordering = ["name"]


class Person(models.Model):
    name = models.CharField(verbose_name=_("Person name"), max_length=100, blank=False)
    lastname = models.CharField(verbose_name=_("Last name"), max_length=100, blank=True)
    firstname = models.CharField(verbose_name=_("First name"), max_length=100, blank=True)
    gender = models.CharField(verbose_name=_("Gender"), max_length=1, choices=(("U", _("Unknown gender")), ("M", _("Male")), ("F", _("Female")), ("O", _("Other"))), default="U")
    #birthdate = models.DateField(verbose_name=_("Birth date"), null=True, blank=True)
    birthdate = models.CharField(verbose_name=_("Birth date"), max_length=10, null=True, blank=True)
    birthplace = models.CharField(verbose_name=_("Birth place"), max_length=100, blank=True)
    #deathdate = models.DateField(verbose_name=_("Death date"), null=True, blank=True)
    deathdate = models.CharField(verbose_name=_("Death date"), max_length=10, null=True, blank=True)
    deathplace = models.CharField(verbose_name=_("Death place"), max_length=100, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Person")
        verbose_name_plural = _("Persons")
        ordering = ["lastname", "name"]


class PersonAttribute(Attribute):
    person = models.ForeignKey(Person, related_name="attributes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Person") + " - " + _("Attribute")
        verbose_name_plural = _("Persons") + " - " + _("Attributes")
        #ordering = ["name"]
        db_table = "base_" + "person_attributes"


class PersonLink(Link):
    person = models.ForeignKey(Person, related_name="links", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Person") + " - " + _("Link")
        verbose_name_plural = _("Persons") + " - " + _("Links")
        #ordering = ["name"]
        db_table = "base_" + "person_links"


class PersonRelation(models.Model):
    type = models.CharField(verbose_name=_("Relation type"), max_length=100, blank=False)  # TODO: clé étrangère ?
    person = models.ForeignKey(Person, related_name="relations", on_delete=models.CASCADE)
    personto = models.ForeignKey(Person, related_name="relations_to", on_delete=models.CASCADE)
    date_start = models.CharField(verbose_name=_("Date start"), max_length=10, null=True, blank=True)
    date_end = models.CharField(verbose_name=_("Date end"), max_length=10, null=True, blank=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)

    class Meta:
        verbose_name = _("Person") + " - " + _("Relation")
        verbose_name_plural = _("Persons") + " - " + _("Relations")
        db_table = "base_" + "person_relations"


class Event(models.Model):
    is_unique = models.BooleanField(verbose_name=_("Unique event"), default=False)
    icon = models.CharField(verbose_name=_("Icon"), max_length=20, blank=False)
    description = models.TextField(verbose_name=_("Description"), blank=True)

    def __str__(self):
        return self.name

    @property
    def name(self):
        name = _("Unknown event")
        names = self.names.all()
        if names:
            current_lang = get_language()
            for nameObj in names:
                name = str(nameObj.name)
                if nameObj.lang.iso1 == current_lang:
                    break
        return name

    class Meta:
        verbose_name = _("Event")
        verbose_name_plural = _("Events")
        db_table = "base_" + "event"


class EventName(models.Model):
    event = models.ForeignKey(Event, related_name="names", on_delete=models.CASCADE)
    lang = models.ForeignKey(Language, verbose_name=pgettext("language", "Language"), on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)

    class Meta:
        verbose_name = _("Event name")
        verbose_name_plural = _("Event names")
        db_table = "base_" + "event_names"
        unique_together = ("event", "lang")


class PersonEvent(models.Model):
    event = models.ForeignKey(Event, related_name="events", on_delete=models.CASCADE)
    person = models.ForeignKey(Person, related_name="events", on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name=_("Date"), null=True, blank=True)
    description = models.TextField(verbose_name=_("Description"), blank=True)

    class Meta:
        verbose_name = _("Person") + " - " + _("Event")
        verbose_name_plural = _("Persons") + " - " + _("Events")
        ordering = ["date"]
        db_table = "base_" + "person_events"


class Group(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False)
    type = models.CharField(verbose_name=_("Type"), max_length=1, choices=(("U", _("Unknown type")), ("S", _("Studies")), ("W", pgettext("to work", "Work")), ("A", _("Group of artists")), ("C", _("Sport club")), ("T", _("Association")), ("O", _("Other"))), default="U")
    info = models.TextField(verbose_name=_("Information"), blank=True)
    creation = models.DateTimeField(verbose_name=_("Creation date"), auto_now_add=True)
    modification = models.DateTimeField(verbose_name=_("Modification date"), auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = pgettext("The group", "Group")
        verbose_name_plural = _("Groups")
        ordering = ["name"]


class GroupAttribute(Attribute):
    group = models.ForeignKey(Group, related_name="attributes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = pgettext("The group", "Group") + " - " + _("Attribute")
        verbose_name_plural = _("Groups") + " - " + _("Attributes")
        ordering = ["name"]
        db_table = "base_" + "group_attributes"


class GroupLink(Link):
    group = models.ForeignKey(Group, related_name="links", on_delete=models.CASCADE)

    class Meta:
        verbose_name = pgettext("The group", "Group") + " - " + _("Link")
        verbose_name_plural = _("Groups") + " - " + _("Links")
        #ordering = ["name"]
        db_table = "base_" + "group_links"


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="members", on_delete=models.CASCADE)
    person = models.ForeignKey(Person, related_name="groups", on_delete=models.CASCADE)
    info = models.CharField(verbose_name=_("Information"), max_length=100, blank=True)
    date_start = models.CharField(verbose_name=_("Date start"), max_length=10, null=True, blank=True)
    date_end = models.CharField(verbose_name=_("Date end"), max_length=10, null=True, blank=True)

    def __str__(self):
        return str(self.group.name) + " / " + str(self.person)

    class Meta:
        verbose_name = pgettext("The group", "Group") + " - " + _("Member")
        verbose_name_plural = _("Groups") + " - " + _("Members")
        db_table = "base_" + "group_members"


class Tag(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100, blank=False, unique=True)
    info = models.TextField(verbose_name=_("Information"), blank=True)
    parent = models.ForeignKey("Tag", verbose_name=_("Parent tag"), related_name="children", on_delete=models.SET_NULL, null=True, blank=True)

base/templates/base/base.html
{% extends 'base_sidebar.html' %}

{% block nav_sidebar %}
  {% include 'base/sidebar.html' %}
{% endblock nav_sidebar %}

base/templates/base/group_add_link.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'group_info' group.id|stringformat:'06d' %}">{{ group.name }}</a> - {% translate 'Add link' %}
{% endblock %}

{% block title %}
{{ group.name }} - {% translate 'Groups' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

base/templates/base/index.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="box box-solid box-info">
            <div class="box-header with-border">
                <h3 class="box-title">{% translate 'Statistics' %}</h3>
            </div>
            <div class="box-body">
                <ul>
                    <li><strong>{% translate 'Persons:' %}</strong> {{ persons_count }}</li>
                    <li><strong>{% translate 'Groups:' %}</strong> {{ groups_count }}</li>
                    <li><strong>{% translate 'Tags:' %}</strong> {{ tags_count }}</li>
                    <li><strong>{% translate 'Countries:' %}</strong> {{ countries_count }}</li>
                    <li><strong>{% translate 'Languages:' %}</strong> {{ languages_count }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

base/templates/base/language_info.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load static %}
{% load mimir %}

{% block title %}
{{ language.name }} - {% translate 'Languages' %} - Mimir
{% endblock %}

{% block content_header %}
<section class="content-header">
  <h1>{{ language.name }}
    {% if perms.base.change_language %}
    <span class="pull-right">
      <a href="{% url 'language_edit' language.code %}" class="btn btn-sm btn-warning">{% translate 'Edit' %}</a>
    </span>
    {% endif %}
  </h1>
</section>
{% endblock content_header %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/datatables/dataTables.min.css' %}" />
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/datatables/datatables.min.js' %}"></script>

<script>
$(function() {
    function makeDataTable(obj, options={}) {
        var opt = {
            "paging"      : true,
            "lengthChange": true,
            "searching"   : true,
            "ordering"    : true,
            "info"        : true,
            "autoWidth"   : true,
            "language": {
                "processing":     "Traitement en cours...",
                "search":         "Rechercher&nbsp;:",
                "lengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
                "info":           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                "infoEmpty":      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                "infoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                "infoPostFix":    "",
                "loadingRecords": "Chargement en cours...",
                "zeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                "emptyTable":     "Aucune donnée disponible dans le tableau.",
                "paginate": {
                    "first":      "Premier",
                    "previous":   "Pr&eacute;c&eacute;dent",
                    "next":       "Suivant",
                    "last":       "Dernier"
                },
                "aria": {
                    "sortAscending":  ": activer pour trier la colonne par ordre croissant",
                    "sortDescending": ": activer pour trier la colonne par ordre décroissant"
                }
            },
        };
        jQuery.extend(opt, options);
        obj.DataTable(opt);
    }

    makeDataTable($("#movies_list"), {"order": [[1, "asc"]]});
    makeDataTable($("#series_list"), {"order": [[0, "asc"]]});
    makeDataTable($("#works_list"), {"order": [[1, "asc"]]});
});
</script>
{% endblock %}

{% block content %}


<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-4">
    <div class="box box-solid box-info">
      <div class="box-body">
        <dl class="dl-horizontal">
          <dt>{% translate 'Name' %}</dt><dd>{{ language.name }}</dd>
          <dt>{% translate 'Code' %}</dt><dd>{{ language.code }}</dd>
          {% if language.iso1 %}<dt>{% translate 'Code ISO 639-1' %}</dt><dd>{{ language.iso1 }}</dd>{% endif %}
          {% if language.iso2 %}<dt>{% translate 'Code ISO 639-2' %}</dt><dd>{{ language.iso2 }}</dd>{% endif %}
          {% if language.iso3 %}<dt>{% translate 'Code ISO 639-3' %}</dt><dd>{{ language.iso3 }}</dd>{% endif %}
        </dl>
      </div>
    </div>
  </div>
</div>

<div class="box box-solid box-info">
  <div class="box-header with-border">
    <h3 class="box-title">{% translate 'Movies' %}</h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>
  <div class="box-body">
    {% if movies|length > 0 %}
    <table class="table table-bordered table-stripped table-hover" id="movies_list">
      <thead>
        <tr>
          <th data-sortable="true">{% translate 'Title' %}</th>
          <th data-sortable="true">{% translate 'Year' %}</th>
          <th data-sortable="true">{% translate 'Duration' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for movie in movies %}
        <tr>
          <td>
            <a href="{% url 'movie_info' movie.id|stringformat:'06d' %}" class="{% if movie.viewed %}movie_viewed{% else %}movie_not_viewed{% endif %}"><i>{{ movie.title }}</i></a>
            {% if movie.title_vo and movie.title_vo != movie.title %} (<i>{{ movie.title_vo }}</i>){% endif %}
          </td>
          <td><span class="hidden">{{ movie.date }}</span>{{ movie.date|date_year }}</td>
          <td><span class="hidden">{{ movie.duration|stringformat:'06d' }}</span>{{ movie.duration|duration_txt }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>{% translate 'No movies.' %}</p>
    {% endif %}
  </div>
</div>

<div class="box box-solid box-info">
  <div class="box-header with-border">
    <h3 class="box-title">{% translate 'Series' %}</h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>
  <div class="box-body">
    {% if language.serie_set.count > 0 %}
    <table class="table table-bordered table-stripped table-hover" id="series_list">
      <thead>
        <tr>
          <th data-sortable="true">{% translate 'Title' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for serie in language.serie_set.all %}
        <tr>
          <td>
            <a href="{% url 'serie_info' serie.id|stringformat:'06d' %}"><i>{{ serie.title }}</i></a>
            {% if serie.title_vo and serie.title_vo != serie.title %} (<i>{{ serie.title_vo}}</i>){% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>{% translate 'No series.' %}</p>
    {% endif %}
  </div>
</div>

<div class="box box-solid box-info">
  <div class="box-header with-border">
    <h3 class="box-title">{% translate 'Books' %}</h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>
  <div class="box-body">
    {% if works|length > 0 %}
    <table class="table table-bordered table-stripped table-hover" id="works_list">
      <thead>
        <tr>
          <th data-sortable="true">{% translate 'Title' %}</th>
          <th data-sortable="true">{% translate 'Year' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for work in works %}
        <tr>
          <td>
            <a href="{% url 'work_info' work.id|stringformat:'06d' %}"><i>{{ work.title }}</i></a>
            {% if work.title_vo and work.title_vo != work.title %} (<i>{{ work.title_vo}}</i>){% endif %}
          </td>
          <td>{% if work.year %}{{ work.year}}{% endif %}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>{% translate 'No books.' %}</p>
    {% endif %}
  </div>
</div>

{% endblock %}

base/templates/base/person_add_event.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content_title %}
<a href="{% url 'person_info' person.id|stringformat:'06d' %}">{{ person.name }}</a> - {% translate 'Add event' %}
{% endblock %}

{% block title %}
{{ person.name }} - {% translate 'Persons' %} - Mimir
{% endblock %}

{% block content %}
{% include 'form_add_object.html' %}
{% endblock %}

base/templates/base/person_add_relation.html
{% extends 'base/base.html' %}

{% load static %}
{% load i18n %}
{% load mimir %}

{% block content_title %}
<a href="{% url 'person_info' person.id|stringformat:'06d' %}">{{ person.name }}</a> - {% translate 'Add relation' %}
{% endblock %}

{% block title %}
{{ person.name }} - {% translate 'Persons' %} - Mimir
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}" media="all" />
{% endblock %}

{% block extra_foot %}
<script src="{% static 'js/select2/select2.min.js' %}"></script>
<script src="{% static 'js/select2/i18n/fr.js' %}"></script>

<script>
$(function() {
    function formatPerson(person) {
        var markup = '';
        if (person.id < 0)
            markup += "<i>{% translate 'Create person' context 'add' %}</i> ";
        markup += '<strong>' + person.name + '</strong>';
        if (person.birth_year || person.death_year) {
            markup += ' (';
            if (person.birth_year)
                markup += person.birth_year;
            markup += '-';
            if (person.death_year)
                markup += person.birth_year;
            markup += ')';
        }
        return markup;
    }

    function formatPersonSelection(person) {
        var value = person.name;
        return value;
    }

    $("#id_personto_id").select2({
        ajax: {
            url: "{% url 'persons_api_search' %}?create=1",
            dataType: 'json',
            delay: 250,
            data: function(params) {
                return {
                    q: params.term,
                    page: params.page
                };
            },
            processResults: function(data, params) {
                params.page = params.page || 1;

                for (var i = 0; i < data.items.length; ++i) {
                    data.items[i]['text'] = data.items[i]['name'];
                }

                return {
                    results: data.items,
                    pagination: {
                        more: data.incomplete_results
                    }
                };
            },
            cache: true
        },
        escapeMarkup: function(markup) { return markup; },
        minimumInputLength: 1,
        templateResult: formatPerson,
        templateSelection: formatPersonSelection,
    }).on("change", function(e) {
        var num = $(this).data('num');
        $('#id_personto_name').val($('#id_personto_id option:selected').text());
        $('#id_personto').val($('#id_personto_id').val());
    });

    if ($('#id_personto').val() != "") {
        $('#id_personto_id').append('<option value="' + $('#id_personto').val() + '" title="' + $('#id_personto_name').val() +'" selected="selected">' + $('#id_personto_name').val() +'</option>');
        $('#id_personto_id').trigger('change');
    }
});
</script>
{% endblock %}

{% block content %}

  {{ form.non_field_errors }}

  {% if form.subject.errors %}
  <ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
  </ol>
  {% endif %}

  <div class="box box-primary">
    <form action="{% url 'person_add_relation' person.id %}" method="post" class="form">
      {% csrf_token %}

      <div class="box-body">
        {% for field in form.hidden_fields %}
          {{ field }} {{ field.errors }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group row{% if field.errors %} has-error{% endif %}">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
          <div class="col-sm-10">{{ field|field_add_class:'form-control input-sm' }}</div>
          {% if field.help_text %}
            <p class="form-text text-muted">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="box-footer">
        <input type="submit" class="btn btn-primary center-block" value="{% translate 'Submit' %}" />
      </div>
    </form>
  </div>

{% endblock %}